### PR TITLE
Added support to remove parameter names from the pattern.

### PR DESCRIPTION
**Pull request by lagnat**
My goal is to offer parameter support to downstream code but I need to clean out the parameters before subscribing up stream.

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]
Looks good! I could see this being useful for people! :D 

Thank you for the PR!

**Comment by RangerMauve** [comment]
Released in v1.2.0

Would you be interested in becoming a collaborator?

**Comment by lagnat** [comment]
I just realized that I didn't add any API doc so that PR will be on the way.  As for being a collaborator, I don't mind but I don't foresee doing much more.

**Comment by RangerMauve** [comment]
That's fine. You don't need to do anything specific, it'll just make it easier to do minor improvements in the future if you find any.

**Pull request merged**
